#ifndef __TEST_MAIN_WINDOW_H
#define __TEST_MAIN_WINDOW_H


#include <QMainWindow>

QT_BEGIN_NAMESPACE
class QAction;
class QMenu;
class QMdiArea;
class QMdiSubWindow;
class QSignalMapper;
QT_END_NAMESPACE


//------------------------------------------------------------------------------
// Типы
// ---
enum inputModeType {
  eNormal  = 0,
  eFindPoint,
  eKbdWaiting
};


//------------------------------------------------------------------------------
// Окно отображения модели
// ---
class MainWindow : public QMainWindow
{
    Q_OBJECT
protected:
    QMdiArea *mdiArea;
    QSignalMapper *windowMapper;

    inputModeType  mode;  // Состояние приложения - режим ввода

public:
    MainWindow();
    virtual ~MainWindow();

public:
    QWidget * createMdiChild();
    void tileSubWindows();
    void cascadeSubWindows();
    QWidget *activeMdiChild();

    bool  IsNormalMode()    const { return mode == eNormal; }
    bool  IsFindPointMode() const { return mode == eFindPoint; }
    bool  IsKbdWaiting()    const { return mode == eKbdWaiting; }

    void  Command( uint wParam );

    void  ExecuteLoop( inputModeType mode ); // Выполнить процесс обработки сообщений
    void  BreakLoop();   // Завершить процесс обработки сообщений

protected:
    virtual void closeEvent( QCloseEvent * event );

protected Q_SLOTS:
    void createNewDocument();
    void openDocument();
    void saveActivDocument();
    void slot_mdiActivated();


public Q_SLOTS:
    void setActiveSubWindow( QWidget *window );
    void setActiveMdiChild( QWidget *window );
    void changeActiveMdiChildState();

private:
    void createActions();
    void createMenus();
    void createStandardToolBar();
    void createStatusBar();
    void setMode( inputModeType set );

public Q_SLOTS:
    void slot_CM_VIEWFRONT                     ();
    void slot_CM_VIEWREAR                      ();
    void slot_CM_VIEWUP                        ();
    void slot_CM_VIEWDOWN                      ();
    void slot_CM_VIEWLEFT                      ();
    void slot_CM_VIEWRIGHT                     ();
    void slot_CM_VIEWISO                       ();
    void slot_CM_FILEOPEN                      ();
    void slot_CM_FILESAVE                      ();
    void slot_CM_FILEADD                       ();
    void slot_CM_FILENEW                       ();
    void slot_CM_FILETAKE                      ();
    void slot_CM_SAT_READ                      ();
    void slot_CM_IGES_READ                     ();
    void slot_CM_XT_READ                       ();
    void slot_CM_STEP_READ                     ();
    void slot_CM_FILEEXPORT                    ();
    void slot_CM_SAT_WRITE                     ();
    void slot_CM_IGES_WRITE                    ();
    void slot_CM_XT_WRITE                      ();
    void slot_CM_STEP_WRITE                    ();
    void slot_CM_POINTPOSITION                 ();
    void slot_CM_POINTON_CURVE                 ();
    void slot_CM_N_POINTS_ON_CURVE             ();
    void slot_CM_POINTONPARAMCURVE             ();
    void slot_CM_POINTWEIGHTCENTRE             ();
    void slot_CM_EDITINTERSECT                 ();
    void slot_CM_POINTINTERSECT                ();
    void slot_CM_EDITSELF_INTERSECT            ();
    void slot_CM_LINEPNTPNT                    ();
    void slot_CM_LINEPNTANLGE0X                ();
    void slot_CM_LINEPOINTANGLE                ();
    void slot_CM_LINEPNTDIST                   ();
    void slot_CM_LINEPRLPNT                    ();
    void slot_CM_LINEPRPPNT                    ();
    void slot_CM_LINEPNTTANG                   ();
    void slot_CM_LINETAN2CIR                   ();
    void slot_CM_LINEANGLETAN_CIRCLE           ();
    void slot_CM_LINEBISECTOR                  ();
    void slot_CM_GORISONTALLINE                ();
    void slot_CM_VERTICALLINE                  ();
    void slot_CM_CIRCLETHREEPOINTS             ();
    void slot_CM_CIRCLECENTREPOINTON           ();
    void slot_CM_CIRCLECENTRERADIUS            ();
    void slot_CM_CIRCLERADIUSTWOPOINTS         ();
    void slot_CM_CIRCLECENTREONRADIUSPOINTON   ();
    void slot_CM_CIRCLECENTREONTWOPOINTS       ();
    void slot_CM_CIRCLETANENTITYCENTRE         ();
    void slot_CM_CIRCLETANENTITYTWOPOINTS      ();
    void slot_CM_CIRCLETANENTITYRADIUSPOINTON  ();
    void slot_CM_CIRCLETANTWOENTITIESPOINTON   ();
    void slot_CM_CIRCLETANTWOENTITIESRADIUS    ();
    void slot_CM_CIRCLETANTHREEENTITIES        ();
    void slot_CM_NEWARC_3_POINTS               ();
    void slot_CM_ARC2POINTSRADIUS              ();
    void slot_CM_ARCCENTRE2POINTS              ();
    void slot_CM_ARCCIRCLE2POINTS              ();
    void slot_CM_ARCTANGENTCURVE2POINTS        ();
    void slot_CM_ARCTANGENTCURVERADPOINTON     ();
    void slot_CM_ELLIPSECENTRE3POINTS          ();
    void slot_CM_ELLIPSE3POINTS                ();
    void slot_CM_ELLIPSECENTRE_AB              ();
    void slot_CM_ELLIPSE_TANGENT2CURVES        ();
    void slot_CM_NEWELLIPSEARC                 ();
    void slot_CM_NEWCONIC                      ();
    void slot_CM_NEWSEGMENTPOINTPOINT          ();
    void slot_CM_NEWLINESEGDMIN                ();
    void slot_CM_NEWPOLYLINE                   ();
    void slot_CM_RECTANGLE                     ();
    void slot_CM_REGULARPOLYGON                ();
    void slot_CM_NEWCBSPLN2D                   ();
    void slot_CM_NEWHERMIT                     ();
    void slot_CM_NEWBEZIER                     ();
    void slot_CM_NEWBSPLINE                    ();
    void slot_CM_SPLINE_EQUID                  ();
    void slot_CM_NEWOFFSETEXTENDED             ();
    void slot_CM_NEWPLANECURVEBYSPACE          ();
    void slot_CM_SPLINENURBS                   ();
    void slot_CM_NEWEDGEMAPONPLANE             ();
    void slot_CM_NEWCONTOUR                    ();
    void slot_CM_NEWENVELOPCONTOUR             ();
    void slot_CM_HANDENVELOPE                  ();
    void slot_CM_CONTOUREQUID                  ();
    void slot_CM_CONTOURFILLET                 ();
    void slot_CM_CONTOURCHAMFER                ();
    void slot_CM_CONTOURBREAK                  ();
    void slot_CM_CONTOURUNITE                  ();
    void slot_CM_CONTOURCROSS                  ();
    void slot_CM_CONTOURSUBSTR                 ();
    void slot_CM_ALL_EMBRACING_CNTRS           ();
    void slot_CM_MAKE_ALL_REGIONS              ();
    void slot_CM_ENCLOSECONTOURS               ();
    void slot_CM_OUTERCONTOURS                 ();
    void slot_CM_RECONSTRUCTCONTOURS           ();
    void slot_CM_MAKEOFFSETCONTOUR             ();
    void slot_CM_MAKESLOPECONTOUR              ();
    void slot_CM_MAKEOFFSETTHINCONTOUR         ();
    void slot_CM_REGIONSBOOLEANOPER            ();
    void slot_CM_NEWCONTOURWITHBREAKS          ();
    void slot_CM_CREATECNTRSMULTILINE          ();
    void slot_CM_CREATEMULTILINE               ();
    void slot_CM_NEWPOINT                      ();
    void slot_CM_NEWNEARPOINTONCURVE           ();
    void slot_CM_NEWPOINTONCURVE               ();
    void slot_CM_NEWCURVEISOCLINAL             ();
    void slot_CM_NEWEVENPARAM                  ();
    void slot_CM_NEWEVENLENGTH                 ();
    void slot_CM_DISTANCEALONG                 ();
    void slot_CM_CREATECURVEISOPOINTS          ();
    void slot_CM_NEWNEARPOINTONSURFACE         ();
    void slot_CM_NEWPOINTONSURFACE             ();
    void slot_CM_NEWDIRECTPOINTONSURFACE       ();
    void slot_CM_NEWSURFACEISOCLINAL           ();
    void slot_CM_NEWPOINTS_ON_SURFACE          ();
    void slot_CM_NEWPOINTONSOLID               ();
    void slot_CM_NEWDIRECTPOINTONSOLID         ();
    void slot_CM_NEWPOINTCURVECROSSING         ();
    void slot_CM_NEWPOINTCURVESURFACE          ();
    void slot_CM_NEWPOINTCURVESOLID            ();
    void slot_CM_NEWLINE3D                     ();
    void slot_CM_NEWLINEPOINTPERPCURVE         ();
    void slot_CM_NEWLINEPOINTPERPSURFACE       ();
    void slot_CM_NEWLINEPOINTPERPSOLID         ();
    void slot_CM_NEWLINEPLANEPLANE             ();
    void slot_CM_RECTANGLEONPLANE              ();
    void slot_CM_NEWPLANECBSPLN                ();
    void slot_CM_NEWPLANENURBS                 ();
    void slot_CM_NEWPLANEOFFSET                ();
    void slot_CM_NEWCONTOURONPLANE             ();
    void slot_CM_NEWCURVEBYPLANE               ();
    void slot_CM_GETPLANECURVE                 ();
    void slot_CM_NEWCIRCLE3D                   ();
    void slot_CM_NEWCIRCLE3DBYCENTRE           ();
    void slot_CM_NEWCIRCLE3DBYPOINTS           ();
    void slot_CM_NEWELLIPSE3D                  ();
    void slot_CM_NEWNURBSCONIC3D_1             ();
    void slot_CM_NEWNURBSCONIC3D_2             ();
    void slot_CM_NEWNURBSCONIC3D_3             ();
    void slot_CM_NEWNURBSCONIC3D_4             ();
    void slot_CM_NEWNURBSCONIC3D_5             ();
    void slot_CM_NEWNURBSCONIC3D_6             ();
    void slot_CM_NEWLINESEGMENT3D              ();
    void slot_CM_NEWPOLYLINE3D                 ();
    void slot_CM_NEWCUBICSPLINE3D              ();
    void slot_CM_NEWHERMIT3D                   ();
    void slot_CM_NEWBEZIER3D                   ();
    void slot_CM_NEWNURBS3D                    ();
    void slot_CM_NEWNURBS3D_WITH_MATING        ();
    void slot_CM_NEWARC3D                      ();
    void slot_CM_NEWARC3DBYPOINTS              ();
    void slot_CM_NEWSPIRALCURVE                ();
    void slot_CM_NEWCONTOUR3D                  ();
    void slot_CM_CURVE_B_SPLINE                ();
    void slot_CM_NEWTRIMMEDCURVE3D             ();
    void slot_CM_NEWEXTENDEDCURVE3D            ();
    void slot_CM_NEWOFFSETCURVE3D              ();
    void slot_CM_NEWCURVESBRIDGE3D             ();
    void slot_CM_NEWCURVESCOUPLE3D             ();
    void slot_CM_NEWCURVESFILLET3D             ();
    void slot_CM_NEWCURVESCONNCURVE3D          ();
    void slot_CM_NEWCONTOUR3DBYCURVES          ();
    void slot_CM_NEWFILLETCONTOUR3DBYCURVES    ();
    void slot_CM_NEWCURVE_BY_TWO_PROJECTIONS   ();
    void slot_CM_NEWSPACECURVEBYPLANE          ();
    void slot_CM_TRANSLATECURVETONURBS         ();
    void slot_CM_APPROXBYARCS                  ();
    void slot_CM_NEWSURFACEBORDER              ();
    void slot_CM_NEWCURVEONSURFACE             ();
    void slot_CM_NEWCURVEDIRECTVECTOR          ();
    void slot_CM_NEWPROJECTIONCURVE_ON_SURFACE ();
    void slot_CM_NEWCURVE_ON_SURFACE_BY_POINTS ();
    void slot_CM_NEWCURVESWRAPPING             ();
    void slot_CM_NEWEDGESCURVE                 ();
    void slot_CM_NEWFACECONTOUR                ();
    void slot_CM_NEWFACEPROJECTION             ();
    void slot_CM_NEWEDGEMAP                    ();
    void slot_CM_NEWSURFACEINTERSECTION        ();
    void slot_CM_NEWSURFACESOLIDINTERSECT      ();
    void slot_CM_NEWSOLIDINTERSECTION          ();
    void slot_CM_NEWFACESINTERSECTION          ();
    void slot_CM_NEWCHARCURVE3D                ();
    void slot_CM_NEWPLANE3POINTS               ();
    void slot_CM_NEWPLANE                      ();
    void slot_CM_NEWPLANEEDGE                  ();
    void slot_CM_NEWCYLINDER3POINTS            ();
    void slot_CM_NEWCONE3POINTS                ();
    void slot_CM_NEWSPHERE3POINTS              ();
    void slot_CM_NEWTORUS3POINTS               ();
    void slot_CM_NEWTRIBEZIERSURFACE           ();
    void slot_CM_NEWRECTANGLENURBS             ();
    void slot_CM_NEWSPLINESURFACE              ();
    void slot_CM_NEWSIMPLEXSURFACE             ();
    void slot_CM_NEWSIMPLEXSPLINESURFACE       ();
    void slot_CM_NEWEXTRUSION                  ();
    void slot_CM_NEWREVOLUTION                 ();
    void slot_CM_NEWEXPANSION                  ();
    void slot_CM_NEWEVOLUTION                  ();
    void slot_CM_NEWSPIRALSURFACE              ();
    void slot_CM_NEWRULEDSURFACE               ();
    void slot_CM_NEWSECTORSURFACE              ();
    void slot_CM_NEWCORNERSURFACE              ();
    void slot_CM_NEWCOVERSURFACE               ();
    void slot_CM_NEWLOFTEDSURFACE              ();
    void slot_CM_NEWELEVATIONSURFACE           ();
    void slot_CM_NEWMESHSURFACE                ();
    void slot_CM_NEWNURBSSURFACE               ();
    void slot_CM_NEWOFFSETSURFACE              ();
    void slot_CM_NEWDEFORMEDSURFACE            ();
    void slot_CM_NEWEXTENDEDSURFACE            ();
    void slot_CM_NEWJOINSURFACE                ();
    void slot_CM_NEWCURVEBOUNDEDSURFACE        ();
    void slot_CM_NEWGRIDSURFACE                ();
    void slot_CM_TRANSLATESURFACETONURBS       ();
    void slot_CM_NEW_WIREFRAME_BY_CURVES       ();
    void slot_CM_NEWBLOCKSOLID                 ();
    void slot_CM_NEWWEDGESOLID                 ();
    void slot_CM_NEWCYLINDERSOLID              ();
    void slot_CM_NEWCONESOLID                  ();
    void slot_CM_NEWSPHERESOLID                ();
    void slot_CM_NEWTORUSSOLID                 ();
    void slot_CM_NEWPLATESOLID                 ();
    void slot_CM_NEWPRISMSOLID                 ();
    void slot_CM_NEWPYRAMIDSOLID               ();
    void slot_CM_NEWNURBSBLOCKSOLID            ();
    void slot_CM_NEWCURVEEXTRUSIONSOLID        ();
    void slot_CM_NEWCURVE3DEXTRUSIONSOLID      ();
    void slot_CM_NEWCURVEREVOLUTIONSOLID       ();
    void slot_CM_NEWCURVE3DREVOLUTIONSOLID     ();
    void slot_CM_NEWCURVEEVOLUTIONSOLID        ();
    void slot_CM_NEWCURVELOFTEDSOLID           ();
    void slot_CM_NEWCURVELOFTEDSOLID_CL        ();
    void slot_CM_NEWRULEDSOLID                 ();
    void slot_CM_NEWSHEETSOLID                 ();
    void slot_CM_NEWELEMENTARYSOLID            ();
    void slot_CM_BOOLEANUNION                  ();
    void slot_CM_BOSSCURVEEXTRUSIONSOLID       ();
    void slot_CM_BOSSCURVEREVOLUTIONSOLID      ();
    void slot_CM_BOSSCURVEEVOLUTIONSOLID       ();
    void slot_CM_BOSSCURVELOFTEDSOLID          ();
    void slot_CM_BOSSCURVELOFTEDSOLID_CL       ();
    void slot_CM_BOSSUNIONSOLID                ();
    void slot_CM_BOOLEANDIFFERENCE             ();
    void slot_CM_CUTCURVEEXTRUSIONSOLID        ();
    void slot_CM_CUTCURVEREVOLUTIONSOLID       ();
    void slot_CM_CUTCURVEEVOLUTIONSOLID        ();
    void slot_CM_CUTCURVELOFTEDSOLID           ();
    void slot_CM_CUTCURVELOFTEDSOLID_CL        ();
    void slot_CM_CUTUNIONSOLID                 ();
    void slot_CM_BOOLEANINTERSECTION           ();
    void slot_CM_INTERSECTCURVEEXTRUSIONSOLID  ();
    void slot_CM_INTERSECTCURVEREVOLUTIONSOLID ();
    void slot_CM_INTERSECTCURVEEVOLUTIONSOLID  ();
    void slot_CM_INTERSECTCURVELOFTEDSOLID     ();
    void slot_CM_INTERSECTCURVELOFTEDSOLID_CL  ();
    void slot_CM_INTERSECTUNIONSOLID           ();
    void slot_CM_SOLIDFILLET                   ();
    void slot_CM_SOLIDCHANNEL                  ();
    void slot_CM_SOLIDSPAN                     ();
    void slot_CM_SOLIDSMOOTH                   ();
    void slot_CM_SOLIDCHAMFER                  ();
    void slot_CM_SOLIDSLANT1                   ();
    void slot_CM_SOLIDSLANT2                   ();
    void slot_CM_SOLID_CONTOUR_CUT             ();
    void slot_CM_SOLID_SURFACE_CUT             ();
    void slot_CM_SOLID_SHELL_CUT               ();
    void slot_CM_NEWSYMMETRYSOLID              ();
    void slot_CM_NEWTHINSOLID_ONESIDE_OFFSET   ();
    void slot_CM_NEWTHINSOLID_ONESIDE_MONOTHICK();
    void slot_CM_NEWTHINSOLID_ONESIDE_POLYTHICK();
    void slot_CM_FULLFILLETSOLID               ();
    void slot_CM_SOLIDVERTEXFILLET             ();
    void slot_CM_SOLIDNPDRAFT                  ();
    void slot_CM_NEW_SPLIT_SOLID               ();
    void slot_CM_NEWRIBSOLID                   ();
    void slot_CM_NEWRIBSHELL                   ();
    void slot_CM_NEWHOLESOLID                  ();
    void slot_CM_NEWPOCKETSOLID                ();
    void slot_CM_NEWSLOTSOLID                  ();
    void slot_CM_NEWUNIONSOLID                 ();
    void slot_CM_CREATE_PARTSOLID              ();
    void slot_CM_SILHOUETTECONTOURSOLID        ();
    void slot_CM_NEWSOLIDEXTRUSIONSOLID        ();
    void slot_CM_NEWSOLIDREVOLUTIONSOLID       ();
    void slot_CM_NEWSOLIDEVOLUTIONSOLID        ();
    void slot_CM_DUPLICATION_BYGRID            ();
    void slot_CM_DUPLICATION_BYMATRICES        ();
    void slot_CM_THINSOLIDBYSHELL              ();
    void slot_CM_CREATESHEETSOLID              ();
    void slot_CM_BENDOVERSEGMENT               ();
    void slot_CM_JOGSHEETSOLID                 ();
    void slot_CM_BENDBYEDGES                   ();
    void slot_CM_JOINTBEND                     ();
    void slot_CM_SHEETSOLIDPLATE               ();
    void slot_CM_SHEETSOLIDHOLE                ();
    void slot_CM_SHEETSOLIDINTERSECT           ();
    void slot_CM_CLOSECORNER                   ();
    void slot_CM_STAMPSHEETSOLID               ();
    void slot_CM_BEADSHEETSOLID                ();
    void slot_CM_JALOUSIESHEETSOLID            ();
    void slot_CM_CREATERULEDSOLID              ();
    void slot_CM_TRANSFORMEDSOLID              ();
    void slot_CM_REMOVEMODIFIEDSOLID           ();
    void slot_CM_CREATEMODIFIEDSOLID           ();
    void slot_CM_ACTIONMODIFIEDSOLID           ();
    void slot_CM_OFFSETMODIFIEDSOLID           ();
    void slot_CM_FILLETMODIFIEDSOLID           ();
    void slot_CM_SUPPLEMODIFIEDSOLID           ();
    void slot_CM_SUPPLESETCONJUGATION          ();
    void slot_CM_SUPPLESETSIMILARITY           ();
    void slot_CM_SUPPLESETSMOOTHING            ();
    void slot_CM_PURIFYMODIFIEDSOLID           ();
    void slot_CM_MERGERMODIFIEDSOLID           ();
    void slot_CM_NEWNURBSSURFACESHELL          ();
    void slot_CM_NEWCURVEEXTRUSIONSHELL        ();
    void slot_CM_NEWCURVEREVOLUTIONSHELL       ();
    void slot_CM_NEWCURVEEVOLUTIONSHELL        ();
    void slot_CM_NEWCURVELOFTEDSHELL           ();
    void slot_CM_NEWCURVELOFTEDSHELL_CL        ();
    void slot_CM_NEWMESHSHELL                  ();
    void slot_CM_NEWRULSHELL                   ();
    void slot_CM_NEWJOINSOLID                  ();
    void slot_CM_SHELLSURFACE                  ();
    void slot_CM_LOFTEDSHELLBYPOINTS           ();
    void slot_CM_LOFTEDSHELLBYCURVES           ();
    void slot_CM_SOLIDVARIETY                  ();
    void slot_CM_SOLIDEXTERNAL                 ();
    void slot_CM_SOLIDINTERNAL                 ();
    void slot_CM_CUTSHELL_BYCONTOUR            ();
    void slot_CM_CUTSHELL_BYSURFACE            ();
    void slot_CM_CUTSHELL_BYOBJECTS            ();
    void slot_CM_SHELLOFSOLID                  ();
    void slot_CM_OFFSETSHELLBYFACES            ();
    void slot_CM_NEWEXTENSIONSHELL             ();
    void slot_CM_FACESFILLET                   ();
    void slot_CM_SHELLSEW                      ();
    void slot_CM_SOLIDSEW                      ();
    void slot_CM_SHELLPATCH                    ();
    void slot_CM_CURVEPATCH                    ();
    void slot_CM_NEWINSTANCE                   ();
    void slot_CM_NEWASSEMBLY                   ();
    void slot_CM_NEWCURVEHIDEMAP               ();
    void slot_CM_NEWSURFACEHIDEMAP             ();
    void slot_CM_NEWSOLIDHIDEMAP               ();
    void slot_CM_NEWSOLIDSHIDEMAP              ();
    void slot_CM_NEW_SOLID_CONTOUR_SECTION_MAP ();
    void slot_CM_NEW_SOLID_LOCAL_SECTION_MAP   ();
    //void slot_CM_NEW_CONSTRUCTIVE_BY_POINTS    ();
    void slot_CM_DUPLICATEOBJECT               ();
    void slot_CM_MIRRORDUPLICATEOBJECT         ();
    void slot_CM_NEWTHREAD_INSPACE             ();
    void slot_CM_NEWTHREAD_ONSOLID             ();
    void slot_CM_NEWTHREAD_MAPPING_BYPARAMS    ();
    void slot_CM_NEWTHREAD_MAPPING_BYTHREAD    ();
    void slot_CM_MATE_COINCIDENCE              ();
    void slot_CM_MATE_PARALLELISM              ();
    void slot_CM_MATE_PERPENDICULAR            ();
    void slot_CM_MATE_TANGENCY                 ();
    void slot_CM_MATE_CONCENTRIC               ();
    void slot_CM_MATE_DISTANCE                 ();
    void slot_CM_MATE_ANGLE                    ();
    void slot_CM_GC_COINCIDENCE                ();
    void slot_CM_GC_PARALLELISM                ();
    void slot_CM_GC_PERPENDICULAR              ();
    void slot_CM_GC_TANGENCY                   ();
    void slot_CM_GC_CONCENTRIC                 ();
    void slot_CM_GC_DISTANCE                   ();
    void slot_CM_GC_ANGLE                      ();
    void slot_CM_RADIUSDIMENSION               ();
    void slot_CM_EDITMOVE                      ();
    void slot_CM_EDITPLANEROTATE               ();
    void slot_CM_EDITLINEROTATE                ();
    void slot_CM_EDITSCALESELECTED             ();
    void slot_CM_DELETESELECTED                ();
    void slot_CM_REBUILD_ITEM                  ();
    void slot_CM_TRANSLATETOBASIS              ();
    void slot_CM_TRANSLATETOINGOT              ();
    void slot_CM_MESH_TO_BREP                  ();
    void slot_CM_CONVERT_TO_MESH               ();
    void slot_CM_ADDBASISPOINTS                ();
    void slot_CM_EDITPROPERTY                  ();
    void slot_CM_MOVEOBJECT                    ();
    void slot_CM_PLANEROTATEOBJECT             ();
    void slot_CM_LINEROTATEOBJECT              ();
    void slot_CM_SCALEOBJECT                   ();
    void slot_CM_DELETEOBJECT                  ();
    void slot_CM_MOVECPLANE                    ();
    void slot_CM_ROTATEPLANEINVIEW             ();
    void slot_CM_DELETECONSTRUCTIVEPLANE       ();
    void slot_CM_SPLINESETCLOSED               ();
    void slot_CM_SPLINEINVERSE                 ();
    void slot_CM_DELETEPART                    ();
    void slot_CM_DELETEPARTP1P2                ();
    void slot_CM_NEWTRIMMEDCURVE               ();
    void slot_CM_BREAKCURVE                    ();
    void slot_CM_FILLETCURVES                  ();
    void slot_CM_CHAMFERCURVES                 ();
    void slot_CM_SPLINESET_WEIGHTS             ();
    void slot_CM_SPLINENEW_POINT               ();
    void slot_CM_SPLINETANGENT                 ();
    void slot_CM_SPLINETRIMM                   ();
    void slot_CM_SPLINECHANGEPOINT             ();
    void slot_CM_SETDEGREE                     ();
    void slot_CM_SPLINEINSERTKNOT              ();
    void slot_CM_APPARCCURVE                   ();
    void slot_CM_TRANSLATECURVETOCURVE3D       ();
    void slot_CM_TRANSLATECURVETOCONTOURON     ();
    void slot_CM_CONVERTPLANENURBSINTOOPEN     ();
    void slot_CM_CONVERTPLANENURBSINTOCLOSE    ();
    void slot_CM_NORMALIZEOBJECT               ();
    void slot_CM_CONTOURSENSE                  ();
    void slot_CM_DISASSEMBLY                   ();
    void slot_CM_TRANSLATECONTOURTOCONTOURON   ();
    void slot_CM_ADDINVISIBLEPART              ();
    void slot_CM_REPLACEMLTLINESBASISCURVE     ();
    void slot_CM_INSERTMLTLINESVERTEX          ();
    void slot_CM_REMOVEMLTLINESVERTEX          ();
    void slot_CM_SETMLTLINESHOTPOINT           ();
    void slot_CM_DELMLTLINESHOTPOINT           ();
    void slot_CM_SETMLTLINESVERTSMOOTHJOINT    ();
    void slot_CM_SETMLTLINESVERTTRACINGTYPE    ();
    void slot_CM_SETMLTLINESVERTSPECFILLETRAD  ();
    void slot_CM_SETMLTLINESVERTTIPTYPE        ();
    void slot_CM_SETMLTLINESVERTTIPDIR         ();
    void slot_CM_SETMLTLINESRADIUS             ();
    void slot_CM_CHANGEMLTLINESRADIUS          ();
    void slot_CM_ADDMLTLINESRADIUS             ();
    void slot_CM_REMOVEMLTLINESRADIUS          ();
    void slot_CM_SETMLTLINESBEGTIPTYPE         ();
    void slot_CM_SETMLTLINESBEGTIPPARAM        ();
    void slot_CM_SETMLTLINESENDTIPTYPE         ();
    void slot_CM_SETMLTLINESENDTIPPARAM        ();
    void slot_CM_SETMLTLINESPROCESSCLOSED      ();
    void slot_CM_FILLETMLTLINESBASISCURVE      ();
    void slot_CM_CHAMFERMLTLINESBASISCURVE     ();
    void slot_CM_BREAKMLTLINE                  ();
    void slot_CM_BREAKMLTLINENPARTS            ();
    void slot_CM_DELMLTLINESLASTSEG            ();
    void slot_CM_DELETEPARTMLTLINEP1P2         ();
    void slot_CM_MOVEPOINTALONGLINE            ();
    void slot_CM_CURVESETCLOSED                ();
    void slot_CM_CURVEINVERSE                  ();
    void slot_CM_DELETEMIDLEPART               ();
    void slot_CM_CREATEMIDLEPART               ();
    void slot_CM_CREATEBREAKPARTS              ();
    void slot_CM_MOVECURVEPOINT                ();
    void slot_CM_CURVEADDPOINT                 ();
    void slot_CM_CONVERTNURBSINTOOPEN          ();
    void slot_CM_CONVERTNURBSINTOCLOSE         ();
    void slot_CM_ATTACHNURBSTOOBJECT           ();
    void slot_CM_TRANSLATECURVETOBASIS         ();
    void slot_CM_TRANSLATECURVE3DTOCURVE       ();
    void slot_CM_CURVEADDKNOTE                 ();
    void slot_CM_CURVEREMOVEKNOTE              ();
    void slot_CM_REDUCE_NURBS_DEGREE           ();
    void slot_CM_GOSURFACETHROUGHPLANE         ();
    void slot_CM_GOSURFACETHROUGHPOINT         ();
    void slot_CM_CONVERTNURBSSURFACEINTOOPEN   ();
    void slot_CM_CONVERTNURBSSURFACEINTOCLOSE  ();
    void slot_CM_TRANSLATESURFACETOBASIS       ();
    void slot_CM_REBUILD_SHELL                 ();
    void slot_CM_REBUILD_SHELL_WITHCOPYMODE    ();
    void slot_CM_TRANSLATESOLIDTOBASIS         ();
    void slot_CM_TRANSLATESOLIDTOSURFACES      ();
    void slot_CM_BREAKSOLIDTOPARTS             ();
    void slot_CM_DELETE_ITEM_CREATORS          ();
    void slot_CM_BREAKSOLIDONPARTS             ();
    void slot_CM_UNIFYOWNCOMPLANARFACES        ();
    void slot_CM_SOLIDENDMOVE                  ();
    void slot_CM_SOLIDFINISH                   ();
    void slot_CM_SOLIDENDCUT                   ();
    void slot_CM_SOLIDCREATORDELETE            ();
    void slot_CM_BEND                          ();
    void slot_CM_UNBEND                        ();
    void slot_CM_ADD_ATTTRIBUTE                ();
    void slot_CM_MODTHREAD_ISMATEDTHREADS      ();
    void slot_CM_MODTHREAD_ISBODYTHREAD        ();
    void slot_CM_MODTHREAD_ADAPTTOBODY         ();
    void slot_CM_EDITSELECTALL                 ();
    void slot_CM_EDITUNSELECTALL               ();
    void slot_CM_EDITREVERSSELECTALL           ();
    void slot_CM_SELECTBYCPLANE                ();
    void slot_CM_SELECTALLPOINTS               ();
    void slot_CM_SELECTALLCURVES               ();
    void slot_CM_SELECTLINE                    ();
    void slot_CM_SELECTPOLYCURVE               ();
    void slot_CM_SELECTINTERSECTIONCURVE       ();
    void slot_CM_SELECTCONTOURS2D              ();
    void slot_CM_SELECTCONTOURS3D              ();
    void slot_CM_SELECTCONTOURSONSURFACE       ();
    void slot_CM_SELECTALLSURFACES             ();
    void slot_CM_SELECTPLANE                   ();
    void slot_CM_SELECTELEMENTARYSURFACE       ();
    void slot_CM_SELECTSWEPTSURFACE            ();
    void slot_CM_SELECTPOLYSURFACE             ();
    void slot_CM_SELECTOFFSETSURFACE           ();
    void slot_CM_SELECTCURVEBOUNDEDSURFACE     ();
    void slot_CM_SELECT_ALL_SOLIDS             ();
    void slot_CM_SELECT_CLOSED_SOLIDS          ();
    void slot_CM_SELECT_UNCLOSED_SOLIDS        ();
    void slot_CM_CUTMODELOBJECTS               ();
    void slot_CM_EDITREDRAW                    ();
    void slot_CM_CURVEGABARIT                  ();
    void slot_CM_SURFACEGABARIT                ();
    void slot_CM_FACEGABARIT                   ();
    void slot_CM_SOLIDGABARIT                  ();
    void slot_CM_LOCALGABARIT_CURVE2D          ();
    void slot_CM_LOCALGABARIT_CURVE3D          ();
    void slot_CM_LOCALGABARIT_SURFACE          ();
    void slot_CM_LOCALGABARIT_EDGE             ();
    void slot_CM_LOCALGABARIT_FACE             ();
    void slot_CM_LOCALGABARIT_SOLID            ();
    void slot_CM_FLOOD_FILL_VOLUME             (); 
    void slot_CM_SURF_NORMALS                  ();
    void slot_CM_FACE_NORMALS                  ();
    void slot_CM_MESH_NORMALS                  ();
    void slot_CM_SURFACEHIDE                   ();
    void slot_CM_FACEHIDE                      ();
    void slot_CM_SOLIDHIDE                     ();
    void slot_CM_TRIANGULATESURFACE            ();
    void slot_CM_TRIANGULATESOLID              ();
    void slot_CM_TRIANGULATESOLIDS             ();
    void slot_CM_TRIANGULATEFACE               ();
    void slot_CM_TRIANGULAREREGION             ();
    void slot_CM_SIMPLIFY_TRGN_CONVEX_HULL     ();
    void slot_CM_CURVEMAP                      ();
    void slot_CM_SURFACEMAP                    ();
    void slot_CM_SOLIDMAP                      ();
    void slot_CM_SOLIDFACEMAP                  ();
    void slot_CM_PARAMTRIANGULATEFACE          ();
    void slot_CM_CURVETESTA                    ();
    void slot_CM_SURFACETESTA                  ();
    void slot_CM_MAKESPACEWIREFRAME            ();
    void slot_CM_MAKEPLANEWIREFRAME            ();
    void slot_CM_MAKEWIREFRAMEONPLANE          ();
    void slot_CM_MAKETRIANGLEPOINTFRAME        ();
    void slot_CM_MAKETRIANGLEWIREFRAME         ();
    void slot_CM_MAKETRIANGLEPLANE             ();
    void slot_CM_CURVECURVATURE                ();
    void slot_CM_CURVETORSION                  ();
    void slot_CM_GETSOLIDMASSINERTIA           ();
    void slot_CM_COLLISION_CONSTRUCT_BVT_NODES ();
    void slot_CM_COLLISION_DISTANCE_QUERY      ();
    void slot_CM_COLLISION_INTERFERENCE_SOLIDS ();
    void slot_CM_COLLISION_INTERFERENCE_MESHES ();
    void slot_CM_CROSS_BOOLEAN                 ();
    void slot_CM_FIND_TOUCHED_FACES            ();
    void slot_CM_SPLIT_TOUCHED_FACES           ();
    void slot_CM_MERGE_SOLIDS                  ();
    void slot_CM_GETCONTOURAREA                ();
    void slot_CM_GETCURVELENGTH                ();
    void slot_CM_GETCURVERADIUS                ();
    void slot_CM_GETEDGEFACESANGLE             ();
    void slot_CM_GETEDGEEDGEANGLE              ();
    void slot_CM_POINTDISTANCETOPOINT          ();
    void slot_CM_GETDISTANCETOPOINT            ();
    void slot_CM_GEOMITEMS_MINDISTANCE         ();
    void slot_CM_TOPOITEMS_MINDISTANCE         ();
    void slot_CM_SURFAXESDISTANCE              ();
    void slot_CM_GEOMITEMS_MAXDISTANCE         ();
    void slot_CM_TOPOITEMS_MAXDISTANCE         ();
    void slot_CM_GRIDDED_SURF_MINMAXDISTANCES  ();
    void slot_CM_SURF_MAX_MIN_CURVATURES       ();
    void slot_CM_FACES_MAX_MIN_CURVATURES      ();
    void slot_CM_GETFACECENTRE                 ();
    void slot_CM_CHECK_SHELL_GEOMETRY          ();
    void slot_CM_CHECK_SHELL_NAMES             ();
    void slot_CM_CHECKIDENTICALBASESURFACES    ();
    void slot_CM_CHECK_SOLIDS_INTERSECT        ();
    void slot_CM_CHECK_CONVEX_HULL_INTERSECT   ();
    void slot_CM_FIND_OVERLAPPING_SIMILAR_FACES();
    void slot_CM_FIND_FACES_EDGES_CARRIERS     ();
    void slot_CM_SHELL_REVERSE                 ();
    void slot_CM_DECOMPOSE_ALL_ASSEMBLIES      ();
    void slot_CM_SET_SOLID_LAST_VERSION        ();
    void slot_CM_ADD_VERTEXEDGES_AS_CURVES     ();
    void slot_CM_ADD_SOLIDEDGES_AS_CURVES      ();
    void slot_CM_ADD_SOLIDVERTS_AS_POINTS      ();
    void slot_CM_RECOGNITIONSPIRALSURFACES     ();
    void slot_CM_CHECK_CURVE2D_SPEED           ();
    void slot_CM_CHECK_CURVE3D_SPEED           ();
    void slot_CM_CHECK_SURFACE_SPEED           ();
    void slot_CM_CREATE_SURFACE_OPER_TESS      ();
    void slot_CM_CHECK_CURVES_TANGENT_MATING   ();
    void slot_CM_CHECK_CURVE2D_SELFINT         ();
    void slot_CM_SHOW_CURVE_DIRECTION          ();
    void slot_CM_COMMON_MATES_TEST             ();
    void slot_CM_MATE_CUBE                     ();
    void slot_CM_MATE_FRACTAL                  ();
    void slot_CM_MATE_DISTRIBUTED_DOF          ();
    void slot_CM_LINEAR_PATTERN                ();
    void slot_CM_ANGULAR_PATTERN               ();
    void slot_CM_GETEDGENUMBER_INFACE          ();
    void slot_CM_GETFACENUMBER                 ();
    void slot_CM_GETEDGENUMBER                 ();
    void slot_CM_GETFACEBYNUMBER               ();
    void slot_CM_GETEDGEBYNUMBER               ();
    void slot_CM_RENDERING                     ();
    void slot_CM_SURFACERENDERING              ();
    void slot_CM_SOLIDRENDERING                ();
    void slot_CM_MANUFACTURING                 ();
    void slot_CM_SETVIEWVECTOR                 ();
    void slot_CM_PRINTPLOTT                    ();
    void slot_CM_PRINTBITMAP                   ();
    void slot_CM_SETOBJECTCOLOR                ();
    void slot_CM_SETCONNECTIONCOLOR            ();
    void slot_CM_SETCOLORSELECTED              ();
    void slot_CM_SETCOLORSELECTEDCONN          ();
    void slot_CM_SETBACKGRCOLOR                ();
    void slot_CM_GLRENDERCOLOR                 ();
    void slot_CM_SETSELECTCOLOR                ();
    void slot_CM_SETMAKEGRID                   ();
    void slot_CM_SET_OGL_VIEWTYPE              ();
    void slot_CM_SETSTYLEWIDTH                 ();
    void slot_CM_SETOBJECTWIDTH                ();
    void slot_CM_ITEMSMERGING                  ();
    void slot_CM_EDIT_SAME_CREATORS            ();
    void slot_CM_UVMESHCOUNT                   ();
    void slot_CM_GLPROPERT                     ();
    void slot_CM_GLAMBIENT                     ();
    void slot_CM_GLDIFFUSE                     ();
    void slot_CM_GLSPECULARITY                 ();
    void slot_CM_GLSHININESS                   ();
    void slot_CM_GLOPACITY                     ();
    void slot_CM_GLEMISSION                    ();
    void slot_CM_SETLIGHTDIRECTION             ();
    void slot_CM_INVISIBLEOBJECT               ();
    void slot_CM_VISIBLEALLOBJECTS             ();
    void slot_CM_VISIBLEPOINTS                 ();
    void slot_CM_VISIBLECURVES                 ();
    void slot_CM_VISIBLESURFACES               ();
    void slot_CM_VISIBLEBODIES                 ();
    void slot_CM_SETDEVIATIONSAG               ();
    void slot_CM_SETVISUALSAG                  ();
    void slot_CM_DELTA_RANGE                   ();
    void slot_CM_DELTA_ANGLE                   ();
    void slot_CM_SETCURSORSTEP                 ();
    void slot_CM_REBUILDTIMERESULTFILE         ();
    void slot_CM_SETCURVEDEGREE                ();
    void slot_CM_SETSURFACEDEGREE              ();
    void slot_CM_SKIP_ASSERTS                  ();
    void slot_CM_SWITCH_DEBUG_DRAW             ();
    void slot_CM_SWITCH_MULTITHREADING         ();
    void slot_CM_VIEWFRONTPROJ                 ();
    void slot_CM_VIEWREARPROJ                  ();
    void slot_CM_VIEWUPPROJ                    ();
    void slot_CM_VIEWDOWNPROJ                  ();
    void slot_CM_VIEWLEFTPROJ                  ();
    void slot_CM_VIEWRIGHTPROJ                 ();
    void slot_CM_VIEWISOPROJ                   ();
    void slot_CM_SETVIEWPLACEMENT              ();
    void slot_CM_SETPROJECTION                 ();
    void slot_CM_SETDEPTH                      ();
    void slot_CM_CHANGESCALE                   ();
    void slot_CM_PTORIGIN                      ();
    void slot_CM_SETVIEWPOINT                  ();
    void slot_CM_HELPABOUT                     ();
    void slot_CM_MAKEUSERCOMAND0               ();
    void slot_CM_MAKEUSERCOMAND1               ();
    void slot_CM_MAKEUSERCOMAND2               ();
    void slot_CM_MAKEUSERCOMAND3               ();
    void slot_CM_MAKEUSERCOMAND4               ();
    void slot_CM_MAKEUSERCOMAND5               ();
    void slot_CM_MAKEUSERCOMAND6               ();
    void slot_CM_MAKEUSERCOMAND7               ();
    void slot_CM_MAKEUSERCOMAND8               ();
    void slot_CM_MAKEUSERCOMAND9               ();
    // Раздел примеров.
    void slot_CM_SAMPLE_PARAMETRIC_SKETCH();  // "Параметрический эскиз", "Parametric sketch")
    void slot_CM_SAMPLE_WRITE_SKETCH();       // "Запись параметрического эскиза", "Write a parametric sketch")
    void slot_CM_SAMPLE_READ_SKETCH();        // "Чтение параметрического эскиза", "Read a parametric sketch")
    void slot_CM_SAMPLE_SPINNING_BLOCK();     // "Угловое сопряжение", "Angular mate")
    void slot_CM_SAMPLE_DODECAHEDRON();       // "Сборка додекаэдра", "Dodecahedron assembly ")
    //---
    void slot_CM_ENTERLICENSEKEY();
    void slot_CM_FITMODELTOWINDOW();

protected:
    QAction*  m_actNewDocument;
    QAction*  m_actOpenDocument;
    QAction*  m_actSaveDocument;
    QAction*  m_actRunUserCommand0;
    QAction*  m_actRunUserCommand1;
    QAction*  m_actRunUserCommand2;
    QAction*  m_actRunUserCommand3;
    QAction*  m_actRunUserCommand4;
    QAction*  m_actRunUserCommand5;
    QAction*  m_actRunUserCommand6;
    QAction*  m_actRunUserCommand7;
    QAction*  m_actRunUserCommand8;
    QAction*  m_actRunUserCommand9;
    QAction*  m_actFitScale;
    QAction*  m_actSetIsometry;
    QAction*  m_actSetFront;
    QAction*  m_actSetBack;
    QAction*  m_actSetTop;
    QAction*  m_actSetBottom;
    QAction*  m_actSetLeft;
    QAction*  m_actSetRight;

private:
    void readSettings();
    void writeSettings();

private:
  friend bool CreateFrameWindow();
};


#endif // __TEST_MAIN_WINDOW_H
